auth0/auth0-java-mvc-common

- build.gradle
Change auth0 dependencies scope to `api` rather than just `implementation`.
Will fix https://github.com/auth0/auth0-java-mvc-common/issues/19
When this library is used on a new project, there should be no need to explicitly add as dependencies the JWT, JWKS RSA or Auth0 Java libraries. This was the behavior observed until version `1.0.2` but changed when the OSS plugin was updated. This PR will revert that behavior.
> Revert auth0 dependencies scope to api (compile)

- build.gradle
- src/main/java/com/auth0/AuthenticationController.java
- src/main/java/com/auth0/RequestProcessorFactory.java
- src/test/java/com/auth0/AuthenticationControllerTest.java
- src/test/java/com/auth0/RequestProcessorFactoryTest.java
Version is now obtained from the jar's manifest. This PR also allows to disable the telemetry header on demand.
> Allow telemetry to dynamically obtain the package version

- build.gradle
This was blocking our sync with maven central as the pom being generated by our plugin is not accurate when using dynamic versions.
> Rollback to fixed dependencies versions

- build.gradle
**Changes**
Bump`auth0-java` dependency to latest, to address CVE-2019-12384 and CVE-2019-12814
**References**
https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-450917
https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-450207
> Update to latest auth0-java

- build.gradle
Targeting JDK 8 and Servlet API 4 in 2.0.0.
* Update source and target compatibility to JDK 8
* Update Servlet API dependency to v4
* Update to latest Bouncy Castle dependency
> Update to JDK 8 and Servlet API 4

- README.md
- src/main/java/com/auth0/AuthCookie.java
- src/main/java/com/auth0/AuthenticationController.java
- src/main/java/com/auth0/AuthorizeUrl.java
- src/main/java/com/auth0/RandomStorage.java
- src/main/java/com/auth0/RequestProcessor.java
- src/main/java/com/auth0/SameSite.java
- src/main/java/com/auth0/StorageUtils.java
- src/main/java/com/auth0/TransientCookieStore.java
- src/test/java/com/auth0/AuthenticationControllerTest.java
- src/test/java/com/auth0/AuthorizeUrlTest.java
- src/test/java/com/auth0/RandomStorageTest.java
- src/test/java/com/auth0/RequestProcessorTest.java
- src/test/java/com/auth0/TransientCookieStoreTest.java
Adds support for SameSite cookie handling.
* Sets the SameSite attribute to "None" if using `form_post` response mode
* Sets a fallback cookie for clients that do not accept SameSite=None yet. Can be turned off by configuration on the `AuthenticationController`
Includes new methods that will store state and nonce in cookies (using session as fallback):
* `AuthenticationController.buildAuthorizeUrl(HttpServletRequest request, HttpServletResponse response, String redirectUri)`
* `AuthenticationController.handle(HttpServletRequest request, HttpServletResponse response)`
* `AuthorizeUrl(AuthAPI client, HttpServletRequest request, HttpServletResponse response, String redirectUrl, String responseType)`
A future PR will add deprecations of the corresponding methods:
* …
> Add SameSite Support

- .gitignore
- src/main/java/com/auth0/AuthorizeUrl.java
- src/main/java/com/auth0/TransientCookieStore.java
- src/test/java/com/auth0/AuthorizeUrlTest.java
- src/test/java/com/auth0/TransientCookieStoreTest.java
Currently, cookies used for the `state` and `nonce` during the authentication flow only set the `Secure` attribute if `SameSite=None` (this happens if the response type includes `id_token`). This change allows configuration to always set the `Secure` attribute, regardless of the SameSite value.
Closes #58
> Allow cookies to always have the Secure attribute if configured

- README.md
Removes the (broken) link to the now removed Spring 4 Quickstart. Add note to see the Spring Boot Quickstart if using Spring Boot 2.
> Remove link to removed Spring Quickstart in README

- README.md
As raised in #73, the README is misleading in its use of the session storage. This change clarifies the documentation to accurately capture the usage of the http session.
#73
> Update README to clarify session usage

- src/main/java/com/auth0/AuthenticationController.java
- src/main/java/com/auth0/RequestProcessor.java
- src/test/java/com/auth0/RequestProcessorTest.java
The `RequestProcessor` (package-private) class currently provides overloaded constructors for creating an instance with different parameters.  This leads to the need create additional constructors as additional functionality is required (e.g., upcoming support for organizations), leading to constructor bloat and chaining.
This PR refactors the `RequestProcessor` to use a builder for creation instead of overloaded constructors,  and updates its usage and tests as necessary.
As can be seen in the commits of this PR, I added a test for the default value of the `useLegacySameSiteCookie` value of the `RequestProcessor` prior to the refactoring, to ensure that the behavior remains the same with the refactoring.
> Request processor refactor to builder

- README.md
- build.gradle
- settings.gradle
- src/main/java/com/auth0/AuthenticationController.java
- src/main/java/com/auth0/AuthorizeUrl.java
- src/main/java/com/auth0/IdTokenVerifier.java
- src/main/java/com/auth0/RequestProcessor.java
- src/test/java/com/auth0/AuthenticationControllerTest.java
- src/test/java/com/auth0/IdTokenVerifierTest.java
This PR adds support for logging into an organization, as well as accepting an invitation to an organization during the invitation login flow.
- Updates `auth0-java` dependency to `1.28.0` to use the Organization features added in that release
- Adds the ability to specify an `organization` and `invitation` when configuring the `AuthtenticationController`
- Updates the `IdTokenVerifier` to verify the `org_id` claim, if the `organization` is specified on the `AuthenticationController`
- Adds documentation to the `README` for using the organizations feature
- https://github.com/auth0/auth0-java/pull/338
In addition to adding unit tests, I created a simple webapp using this change to verify that a user is able to log into an organization, as well as accept an invitation.
> Add support for Organizations feature

- README.md
Updates the guidance around token validation when using Organizations, and links to the [Tokens and Organizations](https://auth0.com/docs/organizations/using-tokens) docs.
> [SDK-2549] Update guidance for token validation with organizations

- README.md
Now that the Organizations feature is GA, removing the feature overview documentation from the README; that information can be found in the linked Auth0 docs.
> Remove summary of Orgs feature from README

- build.gradle
- src/main/java/com/auth0/AuthenticationController.java
- src/test/java/com/auth0/AuthenticationControllerTest.java
This library uses the `AuthAPI` client from `auth0-java` to perform authentication requests using the Auth0 Authentication API. The `AuthAPI` client supports the customization of the networking client through the `HttpOptions` configuration class. This change enables the `AuthenticationController` to be configured with a `HttpOptions` object, which if specified will be used to configure the `AuthAPI` client.
> [SDK-2565] Enable network client configuration

- .idea/compiler.xml
- build.gradle
- settings.gradle
This PR updates the OSS release plugin version to 0.16.0, which makes use of a newer Javadoc HTML template.
I also removed the bintray plugin which is no longer used.
> Update OSS release plugin version

- build.gradle
We are upgrading [java-jwt](https://github.com/auth0/java-jwt) and [jwks-rsa-java](https://github.com/auth0/jwks-rsa-java) library dependency to 3.18.3 and 0.20.1 respectively. This is because of their transitive dependency to vulnerable version of Jackson
[Link](https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2326698)
Since this is a dependency upgrade, we checked it using our existing unit tests
> Update java jwt and jwks lib

- build.gradle
We are upgrading [auth0-java](https://github.com/auth0/auth0-java) library to 1.36.1. This is because of their transitive dependency on the vulnerable version of Jackson
[Link](https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2326698)
Since this is a dependency upgrade, we checked it using our existing unit tests
> Update auth0-java dependency

- build.gradle
This PR bumps the `com.auth0` dependencies to latest versions. This addresses [CVE-2020-36518](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36518) for the transient `jackson-databind` dependency.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36518
> Update auth0 dependencies and address CVE-2020-36518

- build.gradle
This PR bumps the auth0 libraries using jackson-databind dependency to 2.13.2.2 to address [CVE-2020-36518](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36518) in that library
> Bump transitive jackson dependencies in auth0 libraries

- CHANGELOG.md
- README.md
[Full Changelog](https://github.com/auth0/auth0-java-mvc-common/compare/1.9.0...1.9.1)
**Security**
- Bump transitive jackson dependencies in auth0 libraries [\#104](https://github.com/auth0/auth0-java-mvc-common/pull/104) ([poovamraj](https://github.com/poovamraj))
> Release 1.9.1

- build.gradle
Patch to latest version of OkHttp (only used directly for test dependency). We will also the implementation dependency of `auth0-java` once a new release is available containing [this fix](https://github.com/auth0/auth0-java/pull/417) to address [CVE-2021-0341](https://nvd.nist.gov/vuln/detail/CVE-2021-0341)
> Update OkHttp version

- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
Updates the Gradle wrapper to v6.9.2. This resolves a few M1-specific bugs.
> Update to Gradle 6.9.2 and bump OSS plugin version

- .circleci/config.yml
Update ship orb to fix published package versions to prevent attempting to re-publish. See https://github.com/auth0/ship-orb/pull/17 for more info.
> Update ship orb

- CHANGELOG.md
- README.md
[Full Changelog](https://github.com/auth0/auth0-java-mvc-common/compare/1.9.3...1.9.4)
This patch release does not contain any functional changes, but is being released using an updated signing key for verification as part of our commitment to best security practices. 
Please review [the README note for additional details.](https://github.com/auth0/auth0-java-mvc-common/blob/master/README.md)
**Security**
- Update dependencies [\#124](https://github.com/auth0/auth0-java-mvc-common/pull/124) ([jimmyjames](https://github.com/jimmyjames))
> Release 1.9.4

- build.gradle
- src/main/java/com/auth0/AuthorizeUrl.java
- src/main/java/com/auth0/InvalidRequestException.java
- src/main/java/com/auth0/RequestProcessor.java
- src/test/java/com/auth0/AuthorizeUrlTest.java
This PR adds support for [Pushed Authorization Requests (PAR)](https://datatracker.ietf.org/doc/html/rfc9126). It does so by providing a new method on `AuthorizeUrl`:
- `fromPushedAuthorizationRequest()`: Given the configured params, executes a Pushed Authorization Request, and uses the resulting `request_uri` to construct the authorize URL with only the `request_uri` and `client_id`.
- https://datatracker.ietf.org/doc/html/rfc9126
- https://github.com/auth0/auth0-java/pull/531
> [SDK-4133] Support Pushed Authorization Requests

- settings.gradle
- src/main/java/com/auth0/AuthCookie.java
- src/main/java/com/auth0/AuthenticationController.java
- src/main/java/com/auth0/AuthorizeUrl.java
- src/main/java/com/auth0/RequestProcessor.java
- src/main/java/com/auth0/TransientCookieStore.java
- src/test/java/com/auth0/AuthenticationControllerTest.java
- src/test/java/com/auth0/TransientCookieStoreTest.java
Prior to this change, transient authentication cookies (state, nonce), are set without a `Path` attribute, which makes them available in the "directory" of the current path.
For customers with login routes outside the path of the callback path, this will result in login failure when attempting to validate the state/nonce.
This change introduces a configuration option on `AuthenticationController`, `withCookiePath(String cookiePath)`, that enables customers to specify a path for the cookies. If not specified, the default path will be used (e.g., no path set, thus the "directory" of the current URL).
https://auth0team.atlassian.net/browse/ESD-27518
In addition to the unit tests, testing was done with an application provided by a customer demonstrating the issue:
* A login servlet that …
> [SDK-4146] Support configurable cookie path

- EXAMPLES.md
- src/main/java/com/auth0/AuthenticationController.java
- src/main/java/com/auth0/IdTokenVerifier.java
- src/test/java/com/auth0/IdTokenVerifierTest.java
Adds support for specifying the organization name to be used on the authorize request (in addition to organization ID).
In addition to the unit tests, the change was tested on a tenant enabling the use of the organization name (as well as organization ID).
> [SDK-4401] Support using organization name

- src/main/java/com/auth0/IdTokenVerifier.java
In #132, we validate the org name by using `equalsIgnoreCase()`, but instead we should use `equals()` with the provided value being lower-cased. The AS will send the claim value as lower-cased.
> Fix org name validation

- .github/workflows/build-and-test.yml
- .github/workflows/dependabot.yml
Use GitHub Actions instead of CircleCi (follow-up change will remove CircleCI).
> [SDK-4434] Use GitHub Actions

- build.gradle
Updates auth0-java to address CVE-2023-3635. See https://github.com/auth0/auth0-java/pull/562
> Update dependencies for CVE-2023-3635

- src/main/java/com/auth0/RandomStorage.java
- src/main/java/com/auth0/RequestProcessor.java
- src/test/java/com/auth0/RandomStorageTest.java
- src/test/java/com/auth0/RequestProcessorTest.java
This PR provides additional information to the error message received when a state validation error occurs. To minimize any potential breaking changes, it:
* Does not introduce any new exception classes
* Does not modify the existing exception messaging (in case clients pattern match on the message), but does add additional messaging to indicate the source of the error (missing auth state param, missing state value, or state mismatch between session/cookie value and auth response param)
Note that the SDK currently needs to support the deprecated methods that use the session for auth state param storage (both for building the auth URL as well as processing the callback). In v2, we should:
* Remove deprecated methods that store auth params in the session
* Provide specific exception types …
> [SDK-4670] Improved state handling errors
