- .circleci/config.yml
> use CI v2.1

- build.gradle
- Updating to latest versions of Auth0 SDKs
- Fixes jackson-databind security vulnerabilities
- https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-455617
`.gradlew clean check` passing
> Update to latest Auth0 dependencies

- build.gradle
Update dependencies to address CVE-2019-14540
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-14540
> Update dependencies to address CVE

- build.gradle
* Update source and target compatibility to JDK 8
* Update Servlet API dependency to v4
* Update to latest Bouncy Castle dependency
> Update to JDK 8 and Servlet 4

- build.gradle
Reverts auth0/auth0-java-mvc-common#45.
Dependency updates will be targeted for the next major.
> Revert "Update to JDK 8 and Servlet 4"

- .codecov.yml
Set the codecov threshold for patch and project to 2%.
> Adjust codecov threshold

- build.gradle
Updates the Auth0 OSS plugin to version 0.10.0
No tests.
> Update Auth0 gradle OSS plugin dependency version

- CHANGELOG.md
- README.md
> Release 1.2.0

- CHANGELOG.md
- README.md
> Release 1.3.0

- build.gradle
> Make bouncycastle dependency testImplementation

- build.gradle
- src/test/java/com/auth0/AuthenticationControllerTest.java
- src/test/java/com/auth0/RequestProcessorTest.java
Updates to the latest dependency versions.
> Update dependency versions

- CHANGELOG.md
- README.md
[Full Changelog](https://github.com/auth0/auth0-java-mvc-common/compare/1.4.0...1.5.0)
**Changed**
- Update dependency versions [\#74](https://github.com/auth0/auth0-java-mvc-common/pull/74) ([jimmyjames](https://github.com/jimmyjames))
> Release 1.5.0

- CHANGELOG.md
- README.md
[Full Changelog](https://github.com/auth0/auth0-java-mvc-common/compare/1.5.0...1.6.0)
**Added**
- Add support for Organizations feature [\#81](https://github.com/auth0/auth0-java-mvc-common/pull/81) ([jimmyjames](https://github.com/jimmyjames))
**Changed**
- Request processor refactor to builder [\#80](https://github.com/auth0/auth0-java-mvc-common/pull/80) ([jimmyjames](https://github.com/jimmyjames))
> Release 1.6.0

- CHANGELOG.md
- README.md
[Full Changelog](https://github.com/auth0/auth0-java-mvc-common/compare/1.6.0...1.7.0)
**Added**
- [SDK-2565] Enable network client configuration [\#86](https://github.com/auth0/auth0-java-mvc-common/pull/86) ([jimmyjames](https://github.com/jimmyjames))
[SDK-2565]: https://auth0team.atlassian.net/browse/SDK-2565
> Release 1.7.0

- build.gradle
This PR bumps the Auth0 dependencies to the most recent releases.
> Update Auth0 libraries to latest

- CHANGELOG.md
- README.md
[Full Changelog](https://github.com/auth0/auth0-java-mvc-common/compare/1.8.0...1.8.1)
**Security**
- Update java jwt and jwks lib [\#98](https://github.com/auth0/auth0-java-mvc-common/pull/98) ([poovamraj](https://github.com/poovamraj))
> Release 1.8.1

- CHANGELOG.md
- README.md
[Full Changelog](https://github.com/auth0/auth0-java-mvc-common/compare/1.8.1...1.8.2)
**Security**
- Update auth0-java dependency [\#100](https://github.com/auth0/auth0-java-mvc-common/pull/100) ([poovamraj](https://github.com/poovamraj))
> Release 1.8.2

- CHANGELOG.md
- README.md
Release 1.9.0. See `CHANGELOG` for release details.
> Release 1.9.0

- CHANGELOG.md
- README.md
See CHANGELOG diff for release contents.
> Release 1.9.2

- .circleci/config.yml
- .gitignore
- .idea/compiler.xml
- .idea/vcs.xml
- .shiprc
- build.gradle
Integrates the ship orb to enable automated releases.
> Integrate ship orb

- .shiprc
Fixes version replacement when using ship.
> escape quotes in ship config

- CHANGELOG.md
- README.md
- build.gradle
**Changed**
- Update to Gradle 6.9.2 and bump OSS plugin version [\#113](https://github.com/auth0/auth0-java-mvc-common/pull/113) ([jimmyjames](https://github.com/jimmyjames))
**Security**
- Update dependencies [\#119](https://github.com/auth0/auth0-java-mvc-common/pull/119) ([jimmyjames](https://github.com/jimmyjames))
> Release 1.9.3

- .circleci/config.yml
Use the latest published version of the ship-orb.
> Use latest ship orb

- build.gradle
Update to latest auth0 dependencies
> Update auth0 dependencies

- .circleci/config.yml
Change to fix the codecov upload in CI
https://github.com/auth0/ruby-auth0/pull/465
> Fix codecov uploader

- CHANGELOG.md
- README.md
**Added**
- Support Pushed Authorization Requests [\#128](https://github.com/auth0/auth0-java-mvc-common/pull/128) ([jimmyjames](https://github.com/jimmyjames))
- Support configurable cookie path [\#129](https://github.com/auth0/auth0-java-mvc-common/pull/129) ([jimmyjames](https://github.com/jimmyjames))
> Release 1.9.5

- CHANGELOG.md
- README.md
**Added**
- Support using organization name [\#132](https://github.com/auth0/auth0-java-mvc-common/pull/132) ([jimmyjames](https://github.com/jimmyjames))
> Release 1.10.0

- .github/actions/rl-scanner/action.yml
- .github/workflows/release.yml
- .github/workflows/rl-secure.yml
- https://github.com/auth0/auth0-java/pull/655/files
> added reversing lab scanner

- .github/workflows/release.yml
> Add RL Integration Name Update

- .github/workflows/build-and-test.yml
- .github/workflows/codeql.yml
- .github/workflows/rl-secure.yml
- .github/workflows/semgrep.yml
Updated github workflow actions
> Updated github actions

- build.gradle
Updated apache commons package version to 3.18
Please include relevant links supporting this change such as a:
- support ticket
- community post
- StackOverflow post
- support forum thread
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
> Updated apache commons package version
